version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  prometheus:
    image: prom/prometheus:v2.7.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    logging: *default-logging

  alertmanager:
    image: prom/alertmanager:v0.16.1
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    logging: *default-logging

  grafana:
    image: grafana/grafana:6.0.0
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    logging: *default-logging

  pushgateway:
    image: prom/pushgateway:v0.7.0
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    logging: *default-logging

  pg_prometheus:
    image: timescale/pg_prometheus
    command: -c synchronous_commit=OFF
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=prom321
    ports:
      - "5432:5432"
    networks:
      - monitor-net
    logging: *default-logging

  prometheus_postgresql_adapter:
    image: timescale/prometheus-postgresql-adapter
    expose:
      - 9201
    ports:
      - "9201:9201"
    depends_on:
      - pg_prometheus
    command: "-pg.host=pg_prometheus -pg.password=${POSTGRES_PASSWORD} -pg.database=prom321 -pg.prometheus-log-samples"
    networks:
      - monitor-net
    logging: *default-logging

networks:
  monitor-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
